// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqerheqqgozufhcwtrmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZXJoZXFxZ296dWZoY3d0cm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Njk2MjEsImV4cCI6MjA1NjE0NTYyMX0.DOXVhkRVAXrbCdY3H5cMZorzTXI7A0onHPqoDlST_MQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);